version: '3.8'

services:
  vault_bot:
    image: rodcordeiro/vault-bot
    container_name: vault_bot
    restart: always
    env_file:
      - .env
    networks:
      - bots
networks:
  bots:
    name: bots_network
    external: true
