version: '3.8'

services:
  vault_bot:
    image: rodcordeiro/vault-bot:latest
    container_name: vault_bot
    restart: always
    env_file:
      - .env
    networks:
      - bots
    logging:
      driver: 'json-file' # You can choose a different driver if needed
      options:
        max-size: '5m' # Maximum size of a single log file
        max-file: '1' # Maximum number of log files to retain

networks:
  bots:
    name: bots_network
    external: true
