version: '3.8'

services:
  vault_db:
    image: mysql:latest
    container_name: vault_db
    restart: on-failure
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vault_db
    ports:
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    networks:
      - vault

networks:
  vault:
    driver: bridge
